routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resources([
    'building' => 'BuildingController',
    'agreementbc' => 'AgreementBCController',
    'agreementbcdetail' => 'AgreementBCDetailController',
    'agreementa' => 'AgreementAController',
    'agreementadetail' => 'AgreementADetailController',
]);

Route::get('/agreementacek','AgreementAController@cek');
Route::get('/agreementbccek','AgreementBCController@cek');

Route::get('/agreementanotdone/{id}','AgreementAController@notdone');
Route::get('/agreementbcnotdone/{id}','AgreementBCController@notdone');

app/Building.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Building extends Model
{
    protected $guarded =[];
}

app/Http/Controllers/BuildingController.php
<?php

namespace App\Http\Controllers;

use App\Building;
use Illuminate\Http\Request;

class BuildingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.building.index',['data'=>Building::latest()->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.building.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Building    ::create($request->all());
        return redirect()->route('building.index')->with('message','Input Success');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Building  $building
     * @return \Illuminate\Http\Response
     */
    public function show(Building $building)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Building  $building
     * @return \Illuminate\Http\Response
     */
    public function edit(Building $building)
    {
        return view('pages.building.edit',['data'=>$building]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Building  $building
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Building $building)
    {
        Building::find($building->id)->update($request->all()); 
        return redirect()->route('building.index')->with('message','Edit Success');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Building  $building
     * @return \Illuminate\Http\Response
     */
    public function destroy(Building $building)
    {
        $building->delete();
        return redirect()->route('building.index')->with('message','Edit Success');
    }
}

resources/views/pages/building/create.blade.php
@extends('layouts.app')

{{-- title-dashboard --}}
@section('title','Create Building')

{{-- icon-page --}}
@section('iconpage')
<i class="feather icon-plus bg-c-blue"></i>
@endsection

{{-- title-dashboard --}}
@section('titlepage','Create Building')

{{-- title-dashboard --}}
@section('descpage','Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem necessitatibus dolorem beatae')

{{-- breadcrumb --}}
@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="index-2.html"><i class="feather icon-home"></i></a>
</li>
<li class="breadcrumb-item"><a href="#!">create building</a> </li>
@endsection

{{-- content --}}
@section('content')
<div class="row">
    <div class="col-sm-12">

        <div class="card">
            <div class="card-header">
                <h5>Create Building</h5>
                <a href="" class="btn btn-secondary btn-sm btn-round float-right "><i class="feather icon-arrow-left"></i>  back</a>
            </div>
            <div class="card-block">
                <form method="post" action="{{route('building.store')}}">
                    @csrf
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Building</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="name">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Company</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="company">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">PIC</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="pic">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Contact</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="contact">
                        </div>
                    </div>
                    <input type="submit" value="Save" class="btn btn-block btn-primary">
                </form>
                
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/building/edit.blade.php
@extends('layouts.app')

{{-- title-dashboard --}}
@section('title','Edit Building')

{{-- icon-page --}}
@section('iconpage')
<i class="feather icon-edit bg-c-blue"></i>
@endsection

{{-- title-dashboard --}}
@section('titlepage','Edit Building')

{{-- title-dashboard --}}
@section('descpage','Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem necessitatibus dolorem beatae')

{{-- breadcrumb --}}
@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="index-2.html"><i class="feather icon-home"></i></a>
</li>
<li class="breadcrumb-item"><a href="#!">Edit building</a> </li>
@endsection

{{-- content --}}
@section('content')
<div class="row">
    <div class="col-sm-12">

        <div class="card">
            <div class="card-header">
                <h5>Edit Building</h5>
                <a href="" class="btn btn-secondary btn-sm btn-round float-right "><i class="feather icon-arrow-left"></i>  back</a>
            </div>
            <div class="card-block">
                <form method="post" action="{{route('building.update',$data)}}">
                    @csrf @method('patch')
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Building</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="name" value="{{$data->name}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Company</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="company" value="{{$data->company}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">PIC</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="pic" value="{{$data->pic}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Contact</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="contact" value="{{$data->contact}}">
                        </div>
                    </div>
                    <input type="submit" value="Update" class="btn btn-block btn-primary">
                </form>
                
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/building/index.blade.php
@extends('layouts.app')

{{-- title-dashboard --}}
@section('title','Building')

{{-- icon-page --}}
@section('iconpage')
<i class="feather icon-grid bg-c-blue"></i>
@endsection

{{-- title-dashboard --}}
@section('titlepage','Building')

{{-- title-dashboard --}}
@section('descpage','Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem necessitatibus dolorem beatae')

{{-- breadcrumb --}}
@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="index-2.html"><i class="feather icon-home"></i></a>
</li>
<li class="breadcrumb-item"><a href="#!">building</a> </li>
@endsection

{{-- content --}}
@section('content')
<div class="row">
    <div class="col-sm-12">

        <div class="card">
            <div class="card-header">
                <h5>Building</h5>
                <a href="{{route('building.create')}}" class="btn btn-success btn-sm btn-round float-right "><i class="feather icon-plus"></i> Add</a>
            </div>
            <div class="card-block">
                <table id="alt-pg-dt" class="table table-striped table-responsive table-bordered nowrap">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Building</th>
                            <th>Company</th>
                            <th>PIC</th>
                            <th>Contact</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody> 
                        @foreach ($data as $item)
                        <tr>
                            <td>{{ $loop->index+1 }}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->company }}</td>
                            <td>{{ $item->pic }}</td>
                            <td>{{ $item->contact }}</td>
                            <td>
                                <div class="row">
                                    <div class="col-6">
                                        <a href class="btn btn-sm btn-info feather icon-edit"><i class=""></i></a>
                                    </div>
                                    <div class="col-6">
                                        <form action="{{route('building.destroy',$item)}}" method="POST">
                                        @csrf @method('delete')
                                            <button href="" class="btn btn-sm btn-danger feather icon-trash"><i class=""></i></button>
                                        </form>
                                    </div>
                                </div>
                            </td>
                        </tr>    
                        @endforeach
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection