routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resources([
    'building' => 'BuildingController',
    'agreementbc' => 'AgreementBCController',
    'agreementbcdetail' => 'AgreementBCDetailController',
    'agreementa' => 'AgreementAController',
    'agreementadetail' => 'AgreementADetailController',
]);

Route::get('/agreementacek','AgreementAController@cek');
Route::get('/agreementbccek','AgreementBCController@cek');

Route::get('/agreementanotdone/{id}','AgreementAController@notdone');
Route::get('/agreementbcnotdone/{id}','AgreementBCController@notdone');

resources/views/layouts/header.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="description"
    content="Admindek Bootstrap admin template made using Bootstrap 4 and it has huge amount of ready made feature, UI components, pages which completely fulfills any dashboard needs." />
<meta name="keywords"
    content="flat ui, admin Admin , Responsive, Landing, Bootstrap, App, Template, Mobile, iOS, Android, apple, creative app">
<meta name="author" content="colorlib" />

<link rel="icon" href="https://colorlib.com/polygon/admindek/files/assets/images/favicon.ico" type="image/x-icon">

<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Quicksand:500,700" rel="stylesheet">

<link rel="stylesheet" type="text/css" href="{{asset('files/bower_components/bootstrap/css/bootstrap.min.css')}}">

<link rel="stylesheet" href="{{asset('files/assets/pages/waves/css/waves.min.css')}}" type="text/css" media="all">

<link rel="stylesheet" type="text/css" href="{{asset('files/assets/icon/feather/css/feather.css')}}">

<link rel="stylesheet" type="text/css" href="{{asset('files/assets/css/font-awesome-n.min.css')}}">

<link rel="stylesheet" href="{{asset('files/bower_components/chartist/css/chartist.css')}}" type="text/css" media="all">
<link rel="stylesheet" type="text/css" href="{{asset('files/bower_components/dropify/css/dropify.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('files/bower_components/jquery.steps/css/jquery.steps.css')}}">
<link rel="stylesheet" type="text/css"
        href="{{asset('files/bower_components/datatables.net-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('files/assets/pages/data-table/css/buttons.dataTables.min.css')}}">
<link rel="stylesheet" type="text/css"
    href="{{asset('files/bower_components/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('files/assets/pages/notification/notification.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('files/assets/css/style.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('files/assets/css/widget.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('files/assets/css/pages.css')}}">

resources/views/layouts/script.blade.php
<script type="text/javascript" src="{{asset('')}}"></script>
<script type="text/javascript" src="{{asset('')}}files/bower_components/jquery-ui/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="{{asset('')}}files/bower_components/popper.js/js/popper.min.js"></script>
<script type="text/javascript" src="{{asset('')}}files/bower_components/bootstrap/js/bootstrap.min.js"></script>

<script src="{{asset('')}}files/assets/pages/waves/js/waves.min.js"></script>

<script type="text/javascript" src="{{asset('')}}files/bower_components/jquery-slimscroll/js/jquery.slimscroll.js"></script>
<script src="{{asset('')}}files/assets/js/pcoded.min.js"></script>
<script src="{{asset('')}}files/assets/js/vertical/vertical-layout.min.js"></script>

    <script src="{{asset('files/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('files/bower_components/datatables.net-buttons/js/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('files/assets/pages/data-table/js/jszip.min.js')}}"></script>
    <script src="{{asset('fil es/assets/pages/data-table/js/pdfmake.min.js')}}"></script>
    <script src="{{asset('files/assets/pages/data-table/js/vfs_fonts.js')}}"></script>
    <script src="{{asset('files/bower_components/datatables.net-buttons/js/buttons.print.min.js')}}"></script>
    <script src="{{asset('files/bower_components/datatables.net-buttons/js/buttons.html5.min.js')}}"></script>
    <script src="{{asset('files/bower_components/datatables.net-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{asset('files/bower_components/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('files/bower_components/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js')}}"></script>
    <script src="{{asset('files/assets/pages/data-table/js/data-table-custom.js')}}"></script>
    
    <script type="text/javascript" src="{{asset('files/bower_components/dropify/js/dropify.min.js')}}"></script>


<script src="{{asset('files/bower_components/jquery.cookie/js/jquery.cookie.js')}}"></script>
<script src="{{asset('files/bower_components/jquery.steps/js/jquery.steps.js')}}"></script>
<script src="{{asset('files/bower_components/jquery-validation/js/jquery.validate.js')}}"></script>
<script type="text/javascript" src="{{asset('files/assets/pages/form-validation/validate.js')}}"></script>
<script src="{{asset('files/assets/pages/forms-wizard-validation/form-wizard.js')}}"></script>

<script type="text/javascript" src="{{asset('files/assets/js/bootstrap-growl.min.js')}}"></script>
    {{-- <script type="text/javascript" src="{{asset('files/assets/pages/notification/notification.js')}}"></script> --}}

<script type="text/javascript" src="{{asset('files/assets/js/script.min.js')}}"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
<script>
        $(document).ready(function(){
            $('.dropify').dropify();
        });
    </script>
@if(session('message'))
<input type="hidden" name="" id="alertnya" value="{{session('message')}}">
<script>
        'use strict';
        var alertnya = document.getElementById('alertnya').value;
        $(document).ready(function() {
        //Welcome Message (not for login page)
        function notify(message, type){
            $.growl({
                message: message
            },{
                type: type,
                allow_dismiss: false,
                label: 'Cancel',
                className: 'btn-xs btn-inverse bg-success',
                placement: {
                    from: 'top',
                    align: 'center'
                },
                delay: 2500,
                animate: {
                        enter: 'animated fadeInRight',
                        exit: 'animated fadeOutRight'
                },
                offset: {
                    x: 30,
                    y: 30
                }
            });
        };
    
       
         notify(alertnya, 'inverse');
       
    });
</script>
@endif
    @yield('scriptpage')
    

resources/views/layouts/sidebar.blade.php
<div class="pcoded-navigation-label">Main Menu</div>
<ul class="pcoded-item pcoded-left-item">
    @if (Auth::user()->role == 'admin') 
    <li class=" ">
        <a href="{{url('/home')}}" class="waves-effect waves-dark">
            <span class="pcoded-micon">
                <i class="feather icon-home"></i>
            </span>
            <span class="pcoded-mtext">Dashboard</span>
        </a>
    </li>
    <li class=" ">
        <a href="{{route('building.index')}}" class="waves-effect waves-dark">
            <span class="pcoded-micon">
                <i class="feather icon-grid"></i>
            </span>
            <span class="pcoded-mtext">Building</span>
        </a>
    </li>
    @endif
    @if (Auth::user()->role == 'a') 
        <li class=" ">
            <a href="{{route('agreementa.index')}}" class="waves-effect waves-dark">
                <span class="pcoded-micon">
                    <i class="feather icon-file"></i>
                </span>
                <span class="pcoded-mtext">Agreement </span>
            </a>
        </li>    
    @endif
    
    @if (Auth::user()->role == 'b' || Auth::user()->role == 'c') 
    <li class=" ">
            <a href="{{route('agreementbc.index')}}" class="waves-effect waves-dark">
                <span class="pcoded-micon">
                    <i class="feather icon-file"></i>
                </span>
                <span class="pcoded-mtext">Agreement</span>
            </a>
        </li>    
    @endif
    

</ul>